name: ui_library
description: Shared UI library for Labar apps using Moon Design System
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  moon_design: ^1.0.0
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  animations: ^2.0.11
  cached_network_image: ^3.4.1
  flutter_boring_avatars: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
